# Generated by Django 4.1.5 on 2023-02-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrecord",
            name="from_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="callrecord",
            name="to_number",
            field=models.PositiveIntegerField(),
        ),
    ]
